# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrei/Documents/Code/Projects/d20Trade

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrei/Documents/Code/Projects/d20Trade

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrei/Documents/Code/Projects/d20Trade/CMakeFiles /home/andrei/Documents/Code/Projects/d20Trade/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrei/Documents/Code/Projects/d20Trade/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named d20Trade

# Build rule for target.
d20Trade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 d20Trade
.PHONY : d20Trade

# fast build rule for target.
d20Trade/fast:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/build
.PHONY : d20Trade/fast

Source/Economy.o: Source/Economy.cpp.o

.PHONY : Source/Economy.o

# target to build an object file
Source/Economy.cpp.o:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Economy.cpp.o
.PHONY : Source/Economy.cpp.o

Source/Economy.i: Source/Economy.cpp.i

.PHONY : Source/Economy.i

# target to preprocess a source file
Source/Economy.cpp.i:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Economy.cpp.i
.PHONY : Source/Economy.cpp.i

Source/Economy.s: Source/Economy.cpp.s

.PHONY : Source/Economy.s

# target to generate assembly for a file
Source/Economy.cpp.s:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Economy.cpp.s
.PHONY : Source/Economy.cpp.s

Source/Industry.o: Source/Industry.cpp.o

.PHONY : Source/Industry.o

# target to build an object file
Source/Industry.cpp.o:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Industry.cpp.o
.PHONY : Source/Industry.cpp.o

Source/Industry.i: Source/Industry.cpp.i

.PHONY : Source/Industry.i

# target to preprocess a source file
Source/Industry.cpp.i:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Industry.cpp.i
.PHONY : Source/Industry.cpp.i

Source/Industry.s: Source/Industry.cpp.s

.PHONY : Source/Industry.s

# target to generate assembly for a file
Source/Industry.cpp.s:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Industry.cpp.s
.PHONY : Source/Industry.cpp.s

Source/Market.o: Source/Market.cpp.o

.PHONY : Source/Market.o

# target to build an object file
Source/Market.cpp.o:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Market.cpp.o
.PHONY : Source/Market.cpp.o

Source/Market.i: Source/Market.cpp.i

.PHONY : Source/Market.i

# target to preprocess a source file
Source/Market.cpp.i:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Market.cpp.i
.PHONY : Source/Market.cpp.i

Source/Market.s: Source/Market.cpp.s

.PHONY : Source/Market.s

# target to generate assembly for a file
Source/Market.cpp.s:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Market.cpp.s
.PHONY : Source/Market.cpp.s

Source/Population.o: Source/Population.cpp.o

.PHONY : Source/Population.o

# target to build an object file
Source/Population.cpp.o:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Population.cpp.o
.PHONY : Source/Population.cpp.o

Source/Population.i: Source/Population.cpp.i

.PHONY : Source/Population.i

# target to preprocess a source file
Source/Population.cpp.i:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Population.cpp.i
.PHONY : Source/Population.cpp.i

Source/Population.s: Source/Population.cpp.s

.PHONY : Source/Population.s

# target to generate assembly for a file
Source/Population.cpp.s:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Population.cpp.s
.PHONY : Source/Population.cpp.s

Source/Product.o: Source/Product.cpp.o

.PHONY : Source/Product.o

# target to build an object file
Source/Product.cpp.o:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Product.cpp.o
.PHONY : Source/Product.cpp.o

Source/Product.i: Source/Product.cpp.i

.PHONY : Source/Product.i

# target to preprocess a source file
Source/Product.cpp.i:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Product.cpp.i
.PHONY : Source/Product.cpp.i

Source/Product.s: Source/Product.cpp.s

.PHONY : Source/Product.s

# target to generate assembly for a file
Source/Product.cpp.s:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Product.cpp.s
.PHONY : Source/Product.cpp.s

Source/Settlement.o: Source/Settlement.cpp.o

.PHONY : Source/Settlement.o

# target to build an object file
Source/Settlement.cpp.o:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Settlement.cpp.o
.PHONY : Source/Settlement.cpp.o

Source/Settlement.i: Source/Settlement.cpp.i

.PHONY : Source/Settlement.i

# target to preprocess a source file
Source/Settlement.cpp.i:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Settlement.cpp.i
.PHONY : Source/Settlement.cpp.i

Source/Settlement.s: Source/Settlement.cpp.s

.PHONY : Source/Settlement.s

# target to generate assembly for a file
Source/Settlement.cpp.s:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/Settlement.cpp.s
.PHONY : Source/Settlement.cpp.s

Source/main.o: Source/main.cpp.o

.PHONY : Source/main.o

# target to build an object file
Source/main.cpp.o:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/main.cpp.o
.PHONY : Source/main.cpp.o

Source/main.i: Source/main.cpp.i

.PHONY : Source/main.i

# target to preprocess a source file
Source/main.cpp.i:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/main.cpp.i
.PHONY : Source/main.cpp.i

Source/main.s: Source/main.cpp.s

.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.cpp.s:
	$(MAKE) -f CMakeFiles/d20Trade.dir/build.make CMakeFiles/d20Trade.dir/Source/main.cpp.s
.PHONY : Source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... d20Trade"
	@echo "... edit_cache"
	@echo "... Source/Economy.o"
	@echo "... Source/Economy.i"
	@echo "... Source/Economy.s"
	@echo "... Source/Industry.o"
	@echo "... Source/Industry.i"
	@echo "... Source/Industry.s"
	@echo "... Source/Market.o"
	@echo "... Source/Market.i"
	@echo "... Source/Market.s"
	@echo "... Source/Population.o"
	@echo "... Source/Population.i"
	@echo "... Source/Population.s"
	@echo "... Source/Product.o"
	@echo "... Source/Product.i"
	@echo "... Source/Product.s"
	@echo "... Source/Settlement.o"
	@echo "... Source/Settlement.i"
	@echo "... Source/Settlement.s"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

